# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-18 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='time',
        ),
    ]
