# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-25 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_remove_room_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tempuser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='room',
            name='password',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tempuser',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Room'),
        ),
    ]
