# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-26 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_auto_20191126_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='room_name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
