# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-19 03:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0005_room_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='role',
            field=models.IntegerField(default=0),
        ),
    ]
