# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-19 04:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0006_tempuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='current_location',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
