# Generated by Django 2.2.7 on 2019-12-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0007_room_current_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='tempuser',
            name='ready',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tempuser',
            name='voted',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tempuser',
            name='voted_for',
            field=models.IntegerField(default=0),
        ),
    ]
